- action:
  - data:
      entity_id: switch.front_room
    service: switch.toggle
  alias: Multi Switch Frontroom Lights
  condition: []
  id: '0'
  trigger:
  - entity_id: switch.front_room_dummy
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: switch.front_room_dummy
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      entity_id: switch.outside_front
    service: switch.turn_on
  alias: Turn on Outside Lights at Sunset
  condition: []
  id: '1516777136949'
  trigger:
  - event: sunset
    platform: sun
- action:
  - data:
      entity_id: switch.outside_front
    service: switch.turn_off
  alias: Turn off Outside Lights at Sunrise
  condition: []
  id: '1516777302406'
  trigger:
  - event: sunrise
    platform: sun
- action:
  - delay: 00:00:01
  - data:
      payload: 'OFF'
      topic: cmnd/sonoffSV3/POWER
    service: mqtt.publish
  - data:
      message: Garage Door status change
      title: The Garage Door just opened/closed
    service: notify.telegram
  alias: Garage Door
  condition: []
  id: '1518323827019'
  trigger:
  - payload: 'ON'
    platform: mqtt
    topic: cmnd/sonoffSV3/POWER
- id: hass_theme
  alias: hass_theme
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id: input_select.hass_theme
  action:
  - service: frontend.set_theme
    data_template:
      name: '{{ states.input_select.hass_theme.state }}'
- action:
  - service: mqtt.publish
  alias: Check Garage at Night
  condition:
  - condition: state
    entity_id: cover.mygarage
    state: open
  id: '1518655257142'
  trigger:
  - at: '23:59:59'
    platform: time
